### ISSUE TITLE
unbound this in 2nd refs example

### ISSUE THREAD

**Issue by lessenadam** [FrontendMasters/react-enlightenment#12]
In the 2nd refs example (https://jsfiddle.net/codylindley/ttfh7mdh/#tabs=js,result,html,resources), the 'this' is unbound when rendering the text input: 

```
<input type="text" ref={function(thisInput) { 
          this.textInput = thisInput}} />
```

causing the ref example to break. You can bind the 'this' or just use an ES6 arrow declaration and it works great :)

**Comment by codylindley** [comment]
Is the jsfiddle not working for you?

**Comment by codylindley** [comment]
Regardless, you are right. Fixing.
