### ISSUE TITLE
6.5 in Notes, possible missing word

### ISSUE THREAD

**Issue by jim80** [FrontendMasters/react-enlightenment#22]
"A key tenet of maintainable front-ends composable components."
should be 
"A key tenet of maintainable front-ends _is_ composable components." ?
That's still not quite right, maybe some thing like 
"A key tenet of maintainable front-ends _is the the ability to compose_ components."

Anyway, just to let you know it doesn't read quite right as it is!

**Comment by codylindley** [comment]
Thanks, fixed and updating now.
